### ISSUE TITLE
"Cannot find module" error

### ISSUE THREAD

**Issue by barberdt** [freakycue/koa-generic-session-mongo#7]
Receiving the following error on application startup.
```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

MongoDB Version: 3.0.3
koa version: 1.0.0
koa-generic-session version: 1.9.2
koa-generic-session-mongo-version: 0.2.2

```javascript
const koa = require('koa');
const session = require('koa-generic-session');
const MongoStore = require('koa-generic-session-mongo');

const app = koa();
app.keys = ['keys', 'keyskeys'];

app.use(session({
  key: 'test.sid',
  store: new MongoStore()
}));

app.listen(3000);
```

Happy to provide more information as needed.

**Comment by freakycue** [comment]
@barberdt, I think it's related to mongodb package, e.g. bson module not building correctly. You can try to `rm -r ./node_modules` and reinstall dependencies.
